import { test, expect } from '@playwright/test';
import { mkdirSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

test('Shared KV stays in one Q-driven polygon and each projection connects real tensors', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await page.getByLabel('模型模板').selectOption('mqa');
  await page.getByRole('button', { name: '拓扑图', exact: true }).click();
  await page.locator('.react-flow__node[data-id="layer_1"]').click();
  await expect(page.getByLabel('qkv_count', { exact: true })).toHaveCount(0);
  await page.getByLabel('num_heads', { exact: true }).fill('8');
  await page.getByRole('button', { name: '三维视图', exact: true }).click();
  await page.getByRole('button', { name: '聚焦选中层', exact: true }).click();
  await page.getByRole('button', { name: '暂停数据流', exact: true }).click();
  await page.getByRole('button', { name: 'H1', exact: true }).click();
  await page.locator('canvas').evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  mkdirSync('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/mqa-single-polygon.png' });
  await page.getByRole('button', { name: '导出图像', exact: true }).click();
  const svgEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'SVG 矢量图', exact: true }).click();
  await (await svgEvent).saveAs('artifacts/mqa-single-polygon.svg');
  const svg = readFileSync('artifacts/mqa-single-polygon.svg', 'utf8');
  expect(svg).toContain('data-sides="10"'); expect(svg).not.toContain('shared-K');
  for (const port of ['q0', 'q1', 'q7', 'k0', 'v0']) expect(svg).toContain(`data-part="b0:${port}"`);
  await page.getByRole('button', { name: '拓扑图', exact: true }).click();
  await page.getByRole('button', { name: '添加输入对象', exact: true }).click();
  const alt = await page.evaluate(() => JSON.parse(localStorage.getItem('tensorlab-project')!).nodes.at(-1).id);
  await page.getByLabel('输入形状', { exact: true }).fill('1,16,64'); await page.getByLabel('输入形状', { exact: true }).press('Tab');
  await page.locator('.react-flow__node[data-id="layer_1"]').click();
  await page.getByLabel('Q/K/V 对象', { exact: true }).selectOption('b0:q0');
  const editor = page.locator('.projection-editor');
  await editor.getByLabel('选择输入对象', { exact: true }).selectOption(alt);
  await editor.getByRole('button', { name: '添加输入连接', exact: true }).click();
  await expect(page.locator('.validation-badge')).toContainText('形状校验通过');
  await page.locator('.inspector-scroll > .connection-editor').getByRole('button', { name: '取消输出对象 Flatten_2', exact: true }).click();
  await editor.getByLabel('选择输出对象', { exact: true }).selectOption('layer_2');
  await editor.getByRole('button', { name: '添加输出连接', exact: true }).click();
  await expect(page.locator('.validation-badge')).toContainText('形状校验通过');
  const graph = await page.evaluate(() => JSON.parse(localStorage.getItem('tensorlab-project')!));
  const response = await request.post('/api/analyze', { data: graph });
  expect(response.ok()).toBe(true); expect((await response.json()).shapes.layer_2).toEqual([1, 128]);
  await page.getByRole('button', { name: '导出代码', exact: true }).click();
  const pythonEvent = page.waitForEvent('download'); await page.getByRole('button', { name: '下载 .py' }).click();
  await (await pythonEvent).saveAs('artifacts/qkv-connected.py');
  expect(readFileSync('artifacts/qkv-connected.py', 'utf8')).toContain('ports["layer_1"]["b0:q0"]');
  expect(execFileSync('.venv/Scripts/python.exe', ['artifacts/qkv-connected.py'], { encoding: 'utf8' })).toContain('Output shape: (1, 10)');
  await page.getByRole('button', { name: '关闭对话框', exact: true }).click();
  // Cyclic port routes must be preserved for editing and block execution.
  await editor.getByLabel('选择输入对象', { exact: true }).selectOption('layer_2');
  await editor.getByRole('button', { name: '添加输入连接', exact: true }).click();
  await expect(page.locator('.validation-badge')).toContainText('结构错误');
  await editor.getByRole('button', { name: '取消输入对象 Flatten_2', exact: true }).click();
  await expect(page.locator('.validation-badge')).toContainText('形状校验通过');
  await page.getByRole('button', { name: '三维视图', exact: true }).click();
  await page.getByRole('button', { name: '重置视角', exact: true }).click();
  await page.getByRole('button', { name: '播放数据流', exact: true }).click();
  const pixels = () => page.locator('canvas').evaluate(canvas => new Promise<{ colored: number; checksum: number }>(resolve => requestAnimationFrame(() => {
    const c = canvas as HTMLCanvasElement, gl = c.getContext('webgl2')!, data = new Uint8Array(c.width * c.height * 4);
    gl.readPixels(0, 0, c.width, c.height, gl.RGBA, gl.UNSIGNED_BYTE, data);
    let colored = 0, checksum = 0; for (let i = 0; i < data.length; i += 4) { if (Math.max(data[i], data[i+1], data[i+2]) - Math.min(data[i], data[i+1], data[i+2]) > 30) colored++; checksum = (checksum + data[i] * (1 + i % 31) + data[i+1]) >>> 0; }
    resolve({ colored, checksum });
  })));
  await expect.poll(async () => (await pixels()).colored).toBeGreaterThan(1000);
  const moving = await pixels(); await page.waitForTimeout(250); expect((await pixels()).checksum).not.toBe(moving.checksum);
  await page.screenshot({ path: 'artifacts/qkv-connections-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '聚焦选中层', exact: true }).click();
  await expect.poll(async () => (await pixels()).colored).toBeGreaterThan(300);
  await page.getByRole('button', { name: 'H1', exact: true }).click();
  if (await page.getByRole('button', { name: '关闭通知', exact: true }).count()) await page.getByRole('button', { name: '关闭通知', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/qkv-connections-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
