"""Generated by TensorLab 3D. Image layout: NCHW; sequence layout: BSE."""
import torch
from torch import nn

"""Attention runtime shared by real training and standalone Python exports.

BSE tensors; non-causal full attention. Independent branches are averaged.
"""
import torch
from torch import nn
from torch.nn import functional as F


class AttentionBranch(nn.Module):
    def __init__(self, embed_dim, num_heads, kv_heads, dropout):
        super().__init__()
        self.num_heads = num_heads
        self.kv_heads = kv_heads
        self.head_dim = embed_dim // num_heads
        self.dropout = dropout
        kv_dim = self.head_dim * kv_heads
        self.q_proj = nn.Linear(embed_dim, embed_dim)
        self.k_proj = nn.Linear(embed_dim, kv_dim)
        self.v_proj = nn.Linear(embed_dim, kv_dim)
        self.out_proj = nn.Linear(embed_dim, embed_dim)

    def forward(self, query, context, overrides=None, prefix=""):
        batch, query_length, embed = query.shape
        overrides = overrides or {}
        projections = {}
        def project(role, layer, source, count):
            default = layer(source).view(batch, source.shape[1], count, self.head_dim)
            heads = []
            for index in range(count):
                port = f"{prefix}{role}{index}"
                if port in overrides:
                    start = index * self.head_dim
                    tensor = F.linear(overrides[port], layer.weight[start:start + self.head_dim], layer.bias[start:start + self.head_dim])
                else:
                    tensor = default[:, :, index]
                projections[port] = tensor
                heads.append(tensor)
            return torch.stack(heads, dim=1)
        q = project("q", self.q_proj, query, self.num_heads)
        k = project("k", self.k_proj, context, self.kv_heads)
        v = project("v", self.v_proj, context, self.kv_heads)
        # Each KV group serves num_heads / kv_heads consecutive Q heads.
        repeats = self.num_heads // self.kv_heads
        if repeats > 1:
            k = k.repeat_interleave(repeats, dim=1)
            v = v.repeat_interleave(repeats, dim=1)
        result = F.scaled_dot_product_attention(q, k, v, dropout_p=self.dropout if self.training else 0.0)
        result = result.transpose(1, 2).contiguous().view(batch, query_length, embed)
        return self.out_proj(result), projections


class TensorLabAttention(nn.Module):
    def __init__(self, embed_dim, num_heads=1, kv_heads=None, dropout=0.1, attention_type="self", branches=1):
        super().__init__()
        kv_heads = (1 if attention_type == "multi_query" else num_heads) if kv_heads is None else kv_heads
        if attention_type not in ("self", "multi_query", "grouped_query", "cross", "multi_branch"):
            raise ValueError("Unknown attention_type")
        if any(isinstance(v, bool) or not isinstance(v, int) or v < 1 for v in (embed_dim, num_heads, kv_heads, branches)):
            raise ValueError("Attention dimensions, heads and branches must be positive integers")
        if embed_dim % num_heads or kv_heads > num_heads or num_heads % kv_heads:
            raise ValueError("embed_dim / num_heads and num_heads / kv_heads must be integers")
        if attention_type in ("self", "multi_branch") and kv_heads != num_heads:
            raise ValueError("Self attention requires kv_heads = num_heads")
        if attention_type == "multi_query" and kv_heads != 1:
            raise ValueError("MQA requires kv_heads = 1")
        if attention_type == "multi_branch" and branches < 2:
            raise ValueError("Multi-Branch attention requires at least two branches")
        self.attention_type = attention_type
        self.num_heads = num_heads
        self.kv_heads = kv_heads
        self.branches = nn.ModuleList([AttentionBranch(embed_dim, num_heads, kv_heads, dropout) for _ in range(branches)])

    def forward(self, query, context=None):
        return self.forward_with_ports(query, context)[0]

    def forward_with_ports(self, query, context=None, overrides=None):
        if self.attention_type == "cross":
            if context is None:
                raise ValueError("Cross-Attention requires Query and Context inputs")
        else:
            if context is not None:
                raise ValueError("Self attention takes a single input")
            context = query
        result = None
        projections = {}
        for index, branch in enumerate(self.branches):
            value, ports = branch(query, context, overrides, f"b{index}:")
            result = value if result is None else result + value
            projections.update(ports)
        return result / len(self.branches), projections


class TensorLabTransformer(nn.Module):
    def __init__(self, embed_dim, num_heads=1, kv_heads=None, ff_dim=128, dropout=0.1, attention_type="self", branches=1, norm_first=True):
        super().__init__()
        if not norm_first:
            raise ValueError("This encoder uses pre-norm residuals")
        self.attention = TensorLabAttention(embed_dim, num_heads, kv_heads, dropout, attention_type, branches)
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout(dropout)
        self.ffn = nn.Sequential(nn.Linear(embed_dim, ff_dim), nn.GELU(), nn.Dropout(dropout), nn.Linear(ff_dim, embed_dim), nn.Dropout(dropout))

    def forward(self, query, context=None):
        return self.forward_with_ports(query, context)[0]

    def forward_with_ports(self, query, context=None, overrides=None):
        # Q and self-attention overrides receive the same pre-norm as the base input.
        overrides = {port: self.norm1(value) if ":q" in port or self.attention.attention_type != "cross" else value for port, value in (overrides or {}).items()}
        attention, ports = self.attention.forward_with_ports(self.norm1(query), context, overrides)
        x = query + self.dropout(attention)
        return x + self.ffn(self.norm2(x)), ports



class VisualModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.ModuleDict({
            "layer_1": TensorLabAttention(embed_dim=64, num_heads=4, kv_heads=1, dropout=0.1, attention_type="cross", branches=1),
            "layer_2": nn.Flatten(start_dim=1),
            "layer_3": nn.Linear(512, 10),
        })

    def forward(self, x):
        input_ids = ["layer_0","context"]
        if isinstance(x, dict):
            if set(x) != set(input_ids):
                raise ValueError("Input dictionary must contain exactly the model's Input node IDs")
        elif len(input_ids) != 1:
            raise ValueError("Multi-input models require a dictionary keyed by Input node ID")
        values = {}
        ports = {}
        values["layer_0"] = x["layer_0"]
        values["context"] = x["context"]
        values["layer_1"], ports["layer_1"] = self.layers["layer_1"].forward_with_ports(values["layer_0"], values["context"], overrides={})
        values["layer_2"] = self.layers["layer_2"](values["layer_1"])
        values["layer_3"] = self.layers["layer_3"](values["layer_2"])
        values["layer_4"] = values["layer_3"]
        return values["layer_4"]


if __name__ == "__main__":
    model = VisualModel().eval()
    sample = {
        "layer_0": torch.randn(1, 8, 64),
        "context": torch.randn(1, 12, 64),
    }
    with torch.no_grad():
        result = model(sample)
    print(model)
    print("Output shape:", tuple(result.shape))
    print("Parameters:", sum(p.numel() for p in model.parameters()))
