"""Generated by TensorLab 3D. Image layout: NCHW; sequence layout: BSE."""
import torch
from torch import nn


class VisualModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.ModuleDict({
            "layer_1": nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1),
            "layer_2": nn.BatchNorm2d(16),
            "layer_3": nn.ReLU(),
            "layer_4": nn.MaxPool2d(kernel_size=2, stride=2, padding=0),
            "layer_5": nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            "layer_6": nn.ReLU(),
            "layer_7": nn.AdaptiveAvgPool2d(1),
            "layer_8": nn.Flatten(start_dim=1),
            "layer_9": nn.Linear(32, 10),
        })

    def forward(self, x):
        input_ids = ["layer_0"]
        if isinstance(x, dict):
            if set(x) != set(input_ids):
                raise ValueError("Input dictionary must contain exactly the model's Input node IDs")
        elif len(input_ids) != 1:
            raise ValueError("Multi-input models require a dictionary keyed by Input node ID")
        values = {}
        ports = {}
        values["layer_0"] = x["layer_0"] if isinstance(x, dict) else x
        values["layer_1"] = self.layers["layer_1"](values["layer_0"])
        values["layer_2"] = self.layers["layer_2"](values["layer_1"])
        values["layer_3"] = self.layers["layer_3"](values["layer_2"])
        values["layer_4"] = self.layers["layer_4"](values["layer_3"])
        values["layer_5"] = self.layers["layer_5"](values["layer_4"])
        values["layer_6"] = self.layers["layer_6"](values["layer_5"])
        values["layer_7"] = self.layers["layer_7"](values["layer_6"])
        values["layer_8"] = self.layers["layer_8"](values["layer_7"])
        values["layer_9"] = self.layers["layer_9"](values["layer_8"])
        values["layer_10"] = values["layer_9"]
        return values["layer_10"]


if __name__ == "__main__":
    model = VisualModel().eval()
    sample = torch.randn(1, 3, 32, 32)
    with torch.no_grad():
        result = model(sample)
    print(model)
    print("Output shape:", tuple(result.shape))
    print("Parameters:", sum(p.numel() for p in model.parameters()))
